# Setting host
- hosts: localhost
  become: yes
  gather_facts: false

  vars:
    minikube_install_dir: '/usr/local/bin'
    minikube_install_path: '{{ minikube_install_dir }}/minikube'
    minikube_mirror: 'https://github.com/kubernetes/minikube/releases/download/v{{ minikube_version }}'
    minikube_os: 'linux'
    minikube_architecture: 'amd64'
    minikube_redis_filename: 'minikube-{{ minikube_os }}-{{ minikube_architecture }}'
    minikube_download_filename: '{{ minikube_redis_filename }}-{{ minikube_version }}'
    minikube_download_dir: '/tmp/minikube'
    minikube_version: '1.12.1'

  tasks:
    - name: create download directory
      file:
        state: directory
        mode: 'u=rwx,go=rx'
        dest: '{{ minikube_download_dir }}'

    - name: download sha256sum
      get_url:
        url: '{{ minikube_mirror }}/{{ minikube_redis_filename }}.sha256'
        dest: '{{ minikube_download_dir }}/{{ minikube_download_filename }}.sha256'
        force: no
        use_proxy: yes
        validate_certs: yes
        mode: 'u=rw,go=r'

    - name: read sha256sum
      slurp:
        src: '{{ minikube_download_dir }}/{{ minikube_download_filename }}.sha256'
      register: minikube_sha256sum

    - name: download Minikube
      get_url:
        url: '{{ minikube_mirror }}/{{ minikube_redis_filename }}'
        dest: '{{ minikube_download_dir }}/{{ minikube_download_filename }}'
        sha256sum: '{{ minikube_sha256sum.content | b64decode | trim }}'
        force: no
        use_proxy: yes
        validate_certs: yes
        mode: 'u=rw,go=r'

    - name: create the Minikube installation dir
      become: yes
      file:
        state: directory
        owner: root
        group: root
        mode: 'u=rwx,go=rx'
        dest: '{{ minikube_install_dir }}'

    - name: install Minikube
      become: yes
      copy:
        src: '{{ minikube_download_dir }}/{{ minikube_download_filename }}'
        remote_src: yes
        dest: '{{ minikube_install_path }}'
        force: yes
        owner: root
        group: root
        mode: 'u=rwx,go=rx'